services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./storage:/app/storage

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: